baseURL = ''
languageCode = 'en-us'
title = 'devocのブログ'
theme = "m10c"
paginate = 8
staticDir = ["static/images", "static/images/2022"]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[menu]
    [[menu.main]]
        identifier = "home"
        name = "ホーム"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "tags"
        name = "タグ"
        url = "/tags/"
        weight = 2

[params]
    author = "devoc"
    avatar = "myicon-hooded.PNG"
    description = "エンジニアですが，技術ブログだけでなく，趣味やお気持ち表明も投稿していきます"
    favicon = "https://pub-41b0c551595f4718a77aa525117fc030.r2.dev/myicon-hooded.PNG"
    images = "https://pbs.twimg.com/profile_images/1351413992799969281/Dn-qlLWJ_400x400.jpg"
    
    [[params.social]]
        icon = "twitter"
        name = "Twitter"
        url = "https://twitter.com/devoc_"
    [[params.social]]
        icon = "github"
        name = "Github"
        url = "https://github.com/devoc09"
    [[params.social]]
        icon = "site"
        name = "devoc's site"
        url = "https://devoc.ninja"
[params.style]
    darkestColor = "#262829"
    darkColor = "#1b1d1e"
    # lightColor = "#afbac4"
    lightColor = "#f0f8ff"
    # lightestColor = "#f8f8f2"
    lightestColor = "#f5f5dc"
    primaryColor = "#e48c22"
