baseURL = ''
languageCode = 'en-us'
title = 'devocのブログ'
theme = "m10c"
paginate = 8
staticDir = ["static/images"]
enableGitInfo = true

[frontmatter]
lastmod = [":git", "lastmod"]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[menu]
    [[menu.main]]
        identifier = "home"
        name = "ホーム"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "tags"
        name = "タグ"
        url = "/tags/"
        weight = 2

[params]
    author = "devoc"
    avatar = "my-icon2.webp"
    description = "Powered by Hugo"
    favicon = "https://pub-41b0c551595f4718a77aa525117fc030.r2.dev/favicon.png"
    images = "https://pub-41b0c551595f4718a77aa525117fc030.r2.dev/my-icon2.png"
    
    [[params.social]]
        icon = "x"
        name = "x"
        url = "https://twitter.com/devoc_"
    [[params.social]]
        icon = "github"
        name = "Github"
        url = "https://github.com/devoc09"
    [[params.social]]
        icon = "site"
        name = "devoc's site"
        url = "https://www.devoc.ninja"
[params.style]
    darkestColor = "#262829"
    darkColor = "#1b1d1e"
    # lightColor = "#afbac4"
    lightColor = "#f0f8ff"
    # lightestColor = "#f8f8f2"
    lightestColor = "#f5f5dc"
    primaryColor = "#e48c22"
